# Generated by Django 6.1 on 2026-08-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile photo of the student', null=True, upload_to='profile_pictures/'),
        ),
    ]
