# Generated by Django 6.1 on 2026-08-27 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(help_text='External id of the opportunity', max_length=100)),
                ('source', models.CharField(choices=[('hackathon', 'Hackathon'), ('other', 'Other')], default='hackathon', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, default='', max_length=1000)),
                ('organizer', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('deadline', models.CharField(blank=True, default='', max_length=200)),
                ('prize', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity_id'), name='unique_saved_opportunity_per_user')],
            },
        ),
    ]
